name: open-games-hs
version: '0.1.0.0'
synopsis: Haskell implementation of open games
category: Math
author: Jules Hedges, André Videla, Philipp Zahn & other contributors
maintainer: philipp.zahn@protonmail
copyright: Jules Hedges, André Videla, Philipp Zahn & other contributors
license: AGPL
extra-source-files:
- README.md

library:
  source-dirs: src
  exposed-modules:
    - OpenGames.Custom.ModifiedRLLens
    - OpenGames.Custom.RLLens
    # - OpenGames.Custom.PrisonersDilemmaRepeated
    # - OpenGames.Custom.PrisonersDilemma
    # - OpenGames.Custom.PrisonersDilemmaExternal
    # - OpenGames.Custom.OptionExercise
    - OpenGames.Custom.RLGeneral
    # - OpenGames.Custom.PD_repeated
    # - OpenGames.Custom.PrisonersDilemma_new
    # - OpenGames.Custom.BoS_repeated
    # - OpenGames.Custom.Gift_exchange_game_repeated
    # - OpenGames.Custom.SimultaneousAuction_repeated
    # - OpenGames.Custom.FPSBA
    - OpenGames.Custom.FPSBA_comp
    # - OpenGames.Custom.HUBA_comp
    - OpenGames.Custom.QLearningGame
    # - OpenGames.Custom.RLGeneral_new
    # - OpenGames.Custom.PD_compositional
    # - OpenGames.Custom.PD_compositional_new
    - OpenGames.Custom.QLens_compositional
    - OpenGames.Custom.PrisonersDilemma_new_comp
    - OpenGames.Custom.BoS_comp
    - OpenGames.Custom.Gift_exchange_game_comp
    - OpenGames.Custom.Automated_QOptimizer_Bimatrix
    # - OpenGames.Custom.Automated_QOptimizer_StrategicGame
    - OpenGames.Custom.Automated_QOptimizer_ExtensiveGame
    - OpenGames.Custom.Evaluation
    - OpenGames.Custom.Games_with_outputs
    # - OpenGames.Custom.QLearning_compositional.MonadicLens
    # - OpenGames.Custom.SimultaneousAuction_repeated_more_players
    # - OpenGames.Custom.SequentialAuction_repeated
    # - OpenGames.Custom.SequentialAuction
    # - OpenGames.Custom.SequentialAuction_continious
    # - OpenGames.Custom.SequentialAuction_procurement
    - OpenGames.Engine.AtomicGames
    - OpenGames.Engine.BayesianGames
    - OpenGames.Engine.Diagnostics
    - OpenGames.Engine.Engine
    - OpenGames.Engine.OpenGames
    - OpenGames.Engine.OpticClass
    - OpenGames.Engine.TLL
    - OpenGames.Preprocessor
    - OpenGames.Preprocessor.BlockSyntax
    - OpenGames.Preprocessor.Codegen
    - OpenGames.Preprocessor.CompileBlock
    - OpenGames.Preprocessor.CompileSyntax
    - OpenGames.Preprocessor.Parser
    - OpenGames.Preprocessor.RuntimeAST
    - Examples.SimultaneousMoves
    - Examples.Bayesian
    - Examples.Decision
    - Examples.SequentialMoves
    - Examples.Auctions.AuctionSupportFunctions
    - Examples.Auctions.ChooseReservePrice
    - Examples.Auctions.DutchAuction
    - Examples.Auctions.SequentialAuction
    - Examples.Auctions.SimultaneousBidAuction
    - Examples.Markov.RepeatedPD
    - Examples.Markov.RepeatedPDNonState
    - Examples.Markov.TwoStageMarkov
    - Examples.Markov.TestSimpleMonteCarlo
    - Examples.Markov.TestSimpleMonteCarlo.Continuation

dependencies:
    - base >=4.7 && <5
    - mtl
    - transformers
    - probability
    - ad
    - poly
    - profunctors
    - template-haskell
    - parsec
    - QuickCheck
    - comonad
    - haskeline
    - hashmap
    - hashable
    - extra
    - fgl
    - graphviz
    - lens
    - typed-process
    - mwc-random
    - random
    - vector
    - criterion
    - random
    - containers
    - array



executables:
  open-games-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - open-games-hs
